name: "PHP Juggle"

description: 

In this challenge, a PHP code snippet that contains a vulnerability that allows an attacker to bypass authentication and gain access to restricted parts of the application will be displayed initially. The code may use weak comparison operators or rely on implicit type conversions to compare user input with hardcoded values.
To solve the challenge, the vulnerability needs to be identified and demonstrated how it can be exploited to bypass authentication. This may involve manipulating input data to coerce the comparison to evaluate to true or using a specific value to trigger a specific behaviour.

value: 100
category: Web
flag: CTF_SDaT{Juggle_Flag_Found!}

